services:
    db:
      image: postgres:13
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data/pgdata
      environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=postgres

volumes:
    postgres-data:
